---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: 'Fornisce istruzioni per l"implementazione e l"inizializzazione dei tool ONTAP per VMware vSphere.' 
---
= Tool ONTAP per la guida rapida di VMware vSphere
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP Tools per VMware vSphere è un plug-in vCenter Server singolo che include VSC, provider VASA e estensioni SRA (Storage Replication Adapter). VSC è consigliato per tutti gli ambienti ONTAP vSphere in quanto configura le impostazioni degli host ESXi e fornisce lo storage ONTAP utilizzando le Best practice. Il provider VASA è necessario per il supporto dei volumi virtuali (vVol) e SRA funziona insieme a VMware Site Recovery Manager.



== Preparazione per l'installazione

Il plug-in viene implementato come appliance virtuale, riducendo il lavoro di installazione e registrazione di ciascun prodotto separatamente con vCenter Server.



=== Requisiti di implementazione

I tool ONTAP possono essere utilizzati con un server Windows vCenter o con un'appliance virtuale vCenter. È necessario implementare i tool ONTAP su un vSphere supportato che include il sistema ESXi.

I requisiti minimi di spazio e dimensionamento dell'host sono:

[cols="25,75"]
|===
| *Sistema* | *Requisiti minimi* 


| Spazio | 2.1 GB per installazioni con thin provisioning, 54.0 GB per installazioni con thick provisioning 


| Dimensionamento dell'host | Memoria consigliata: 12 GB, CPU consigliate: 2 
|===
È necessario conoscere le seguenti licenze:

[cols="25,75"]
|===
| *Licenza* | *Descrizione* 


| SnapMirror | (Facoltativo) necessario per eseguire operazioni di failover per SRA e VASA Provider se u si utilizza la replica vVol. 


| FlexClone | (Facoltativo) necessario per eseguire operazioni di failover di test per SRA e per le operazioni vVol del provider VASA. 
|===
Gli strumenti ONTAP utilizzano le seguenti porte TCP bidirezionali predefinite:

|===
| *Requisiti aggiuntivi* | *Colonna Descrizione* 


| 9083 | Se attivata, il provider VASA e SRA utilizzano questa porta per comunicare con il server vCenter. Questa porta è necessaria anche per ottenere le impostazioni TCP/IP. 


| 443 | A seconda di come sono state configurate le credenziali, VMware vCenter Server e i sistemi storage sono in attesa di comunicazioni sicure su questa porta. 


| 8143 | VSC è in attesa di comunicazioni sicure su questa porta. 


| 7 | VSC invia una richiesta echo a ONTAP per verificare la raggiungibilità ed è necessaria solo quando si aggiunge un sistema storage e può essere disattivata in un secondo momento. 
|===
Requisiti minimi di storage e applicazioni:

|===
| *Storage, host e applicazioni* | *Requisiti di versione* 


| ONTAP | ONTAP 9.1, 9.3, 9.5, 9.6, 9.7, 9.8P1 o versione successiva. 


| VMware vSphere, server vCenter, host ESXi, Site Recovery Manager (SRM), applicazioni plug-in e database colonna 1 | Vedere https://imt.netapp.com/matrix/imt.jsp?components=99343;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità"^] 
|===


=== Requisiti dei tool ONTAP

* Configurare e configurare l'ambiente vCenter Server.
* Scaricare il file .ova.
* Le credenziali di accesso per l'istanza di vCenter Server.
* Eliminare la cache del browser per evitare problemi di cache del browser durante l'implementazione degli strumenti ONTAP.
* Configurare il gateway predefinito che l'appliance virtuale deve utilizzare per rispondere ai ping ICMP.
* Un nome host DNS valido per l'appliance virtuale.
* Scaricare e installare i servizi API di OnCommand per ONTAP 9.6 o versioni precedenti se si desidera visualizzare la dashboard di vVol.
Se si utilizza ONTAP 9.7 o versione successiva, non è necessario registrare i servizi API di OnCommand con il provider VASA.




=== Requisiti opzionali per SRA

Se si sta implementando l'appliance virtuale per l'utilizzo con VMware Site Recovery Manager, è necessario disporre di:
 * Ha scaricato il `.msi` File per il plug-in SRA solo se si desidera configurare la soluzione di disaster recovery di Site Recovery Manager (SRM). colonna 1
 * Ha scaricato il `.tar.gz` File per SRA se si utilizza l'appliance SRM.



== Implementazione degli strumenti ONTAP

.Fasi
. Scaricare il `.ova` dal https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^] Su un sistema client vSphere per l'implementazione degli strumenti ONTAP.
+
È necessario implementare `.ova` File sia sul sito di origine che su quello di destinazione se si sta implementando SRA.

. Accedere a vSphere Web Client e selezionare *Home* > *host e cluster*.
. Fare clic con il pulsante destro del mouse sul data center desiderato, quindi fare clic su *Deploy OVF template* (implementa modello OVF).
. È possibile immettere l'URL del file .ova o accedere alla cartella in cui è stato salvato il file .ova, quindi fare clic su *Avanti*.
. Inserire i dettagli richiesti per completare l'implementazione.
+
È possibile visualizzare lo stato di avanzamento della distribuzione dalla scheda *Tasks* e attendere il completamento della distribuzione.





=== Implementazione di SRA su SRM

È possibile implementare SRA sul server Windows SRM o su 8.2 SRM Appliance.



==== Installazione di SRA sul server SRM Windows

.Fasi
. Scaricare il `.msi` Programma di installazione per il plug-in SRA dal NetApp Support Site.
. Fare doppio clic sul scaricato `.msi` Programma di installazione del plug-in SRA e seguire le istruzioni visualizzate.
. Inserire l'indirizzo IP e la password dell'appliance virtuale implementata per completare l'installazione del plug-in SRA sul server SRM.




==== Caricamento e configurazione di SRA sull'appliance SRM

.Fasi
. Scaricare il `.tar.gz` dal https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^].
. Nella schermata dell'appliance SRM, fare clic su *Storage Replication Adapter* > *New Adapter*.
. Caricare `.tar.gz` File su SRM.
. Eseguire nuovamente la scansione degli adattatori per verificare che i dettagli siano aggiornati nella pagina SRM Storage Replication Adapter.
. Accedere utilizzando l'account amministratore all'appliance SRM utilizzando il putty.
. Passare all'utente root: `su root`
. Nella posizione del log, immettere il comando per ottenere l'ID del docker utilizzato da SRA docker: `docker ps -l`
. Accedere all'ID container: `docker exec -it -u srm <container id> sh`
. Configurare SRM con l'indirizzo IP e la password degli strumenti ONTAP: `perl command.pl -I <va-IP> administrator <va-password>`
Viene visualizzato un messaggio di conferma dell'avvenuta memorizzazione delle credenziali di storage.




==== Aggiornamento delle credenziali SRA

.Fasi
. Eliminare il contenuto della directory /srm/sra/conf usando:
+
.. `cd /srm/sra/conf`
.. `rm -rf *`


. Eseguire il comando perl per configurare SRA con le nuove credenziali:
+
.. `cd /srm/sra/`
.. `perl command.pl -I <va-IP> administrator <va-password>`






==== Abilitazione di provider VASA e SRA

.Fasi
. Accedere al client Web vSphere utilizzando l'indirizzo IP specificato durante l'implementazione.
. Fare clic sull'icona *OTV* e immettere il nome utente e la password specificati durante l'implementazione, quindi fare clic su *Sign in* (Accedi).
. Nel riquadro sinistro di OTV, *Impostazioni > Impostazioni amministrative > Gestisci funzionalità* e abilitare le funzionalità richieste.
+

NOTE: IL provider VASA è attivato per impostazione predefinita. Se si desidera utilizzare la funzionalità di replica per gli archivi dati vVol, utilizzare il pulsante di attivazione/disattivazione Enable vVols Replication.

. Inserire l'indirizzo IP degli strumenti ONTAP e la password dell'amministratore, quindi fare clic su *Apply* (Applica).

