---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: 'Le release 9.x dei tool ONTAP per VMware vSphere supportano l"aggiornamento in-place alla versione più recente.' 
---
= Workflow di implementazione per gli utenti esistenti degli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le release 9.x dei tool ONTAP per VMware vSphere supportano l'aggiornamento in-place alla versione più recente.

Le versioni precedenti di singole applicazioni, come gli strumenti ONTAP, utilizzano un processo di aggiornamento diverso. Se nel programma di installazione è installato VSC, VASA Provider o SRA, eseguire le seguenti operazioni:

. Implementare la versione più recente dei tool ONTAP.
. Eseguire la migrazione dei dati di configurazione esistenti.
+
I dati di configurazione includono le credenziali del sistema di storage e le preferenze presenti in `kaminoprefs.xml` e. `vscPreferences.xml`   file.



link:../configure/reference_set_ipv4_or_ipv6.html["Impostare IPv4 o IPv6 utilizzando il file delle preferenze"]

In molti casi, potrebbe non essere necessario migrare i dati di configurazione. Tuttavia, se i file delle preferenze sono stati personalizzati in precedenza, potrebbe essere necessario esaminarli e apportare modifiche simili ai nuovi strumenti ONTAP implementati. È possibile eseguire una delle seguenti operazioni:

* Utilizzare https://mysupport.netapp.com/tools/index.html["Utility di importazione NetApp per SnapCenter e console di storage virtuale"] Per migrare le credenziali del sistema storage da VSC 6.X e SRA 4.X alla nuova implementazione.
* Aggiungere i sistemi storage ai tool ONTAP appena implementati e specificare le credenziali man mano che vengono aggiunte.


Se si esegue l'aggiornamento dal provider VASA 6.X, è necessario annullare la registrazione del provider VASA prima di eseguire l'aggiornamento. Per ulteriori informazioni, consultare la documentazione relativa alla versione corrente.

Se si esegue anche l'aggiornamento da SRA 4.0 o versioni precedenti:

* Se si utilizza SRA 4.0P1, è necessario prima eseguire l'aggiornamento a SRA9.6 e solo in questo caso è possibile eseguire un aggiornamento in-place di SRA 9.6 alla versione più recente.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Effettua l'aggiornamento alla versione più recente dei tool ONTAP"]

* Se si utilizza SRA 2.1 o 3.0, è necessario prima annotare i dettagli della configurazione del sito esistente.
+
_Guida all'installazione e alla configurazione di Storage Replication Adapter 4.0 per ONTAP_ contiene le istruzioni dettagliate nella sezione "Panoramica sull'aggiornamento". Queste release di SRA utilizzano anche il provider VASA, pertanto è necessario annullare la registrazione del provider VASA e implementare la versione più recente dei tool ONTAP. La versione precedente del server (`.ova`) può essere rimosso al termine dell'aggiornamento.



Per qualsiasi aggiornamento SRA, il software SRA (l'adattatore sul server Site Recovery Manager, installato da `.msi` File) deve essere rimosso dal server Site Recovery Manager. È possibile utilizzare il pannello di controllo del sistema Windows per disinstallare il software e installare il software SRA più recente sul server SRA utilizzando `.msi` file.

Se si dispone dell'implementazione del provider VASA, dopo l'aggiornamento dall'installazione esistente, è necessario configurare le dimensioni della memoria per gli strumenti ONTAP in modo che siano 12 GB utilizzando `Edit Settings` opzione. È inoltre necessario modificare la prenotazione della memoria virtuale. La macchina virtuale deve essere spenta per modificare le dimensioni della memoria.

Se si dispone della versione 7.2 o 7.2.1 degli strumenti ONTAP nell'installazione, non è possibile eseguire direttamente l'aggiornamento alla versione 9.7P1 o successiva degli strumenti ONTAP. È necessario prima aggiornare il programma di installazione esistente alla versione 9.7 dei tool ONTAP, quindi eseguire l'aggiornamento alla versione più recente.

Se si intende implementare la versione più recente dei tool ONTAP, è necessario consultare l'argomento "`requisiti per l'implementazione dei tool ONTAP`". L'argomento "`aggiornamento alla versione 9.8 dei tool ONTAP`" contiene informazioni sull'esecuzione di un aggiornamento in-place.

*Informazioni correlate*

https://mysupport.netapp.com/site/tools[]
