---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: 'Se i plug-in non vengono aggiornati automaticamente dopo la distribuzione o l"aggiornamento degli strumenti di ONTAP, è necessario pulire i pacchetti di plug-in di download memorizzati nella cache nel browser e nel server vCenter per risolvere i problemi di plug-in di vCenter Server.' 
---
= Cancellare i pacchetti di plug-in scaricati dalla cache di vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se i plug-in non vengono aggiornati automaticamente dopo la distribuzione o l'aggiornamento degli strumenti ONTAP, è necessario ripulire i pacchetti di plug-in di download memorizzati nella cache nel browser e nel server vCenter per risolvere i problemi di plug-in di vCenter Server.

*Fasi*

. Disconnettere dal client Web vSphere o dal client vSphere esistente.
. Rimuovere la cache del browser.
. Rimuovere i pacchetti di plug-in cache di vSphere Client.
+
|===


| *Se si utilizza...* | *Eseguire le seguenti operazioni...* 


 a| 
Server Windows vCenter
 a| 
Rimuovere le seguenti cartelle `com.netapp.vasa.vvol.webclient-x.x.x.xxxx`, `com.netapp.nvpf.webclient-x.x.x.xxxx`, e. `com.netapp.vsch5-x.x.x.xxxx` si trova all'indirizzo:

** Percorso di vSphere Web Client: `C:\ProgramData\VMware\vCenterServer\cfg\vsphere-client\vc-packages\vsphere-client-serenity`
** Percorso del client vSphere (HTML5): `C:\ProgramData\VMware\vCenterServer\cfg\vsphere-ui\vc-packages\vsphere-client-serenity`




 a| 
VCSA
 a| 
.. SSH nell'appliance VCSA.
.. Modificare le directory nella directory delle estensioni dell'interfaccia utente del client Web vCenter utilizzando `cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`
.. Rimuovere i pacchetti di plug-in memorizzati nella cache specifici di NetApp utilizzando `rm -rf` comandi:
Esempio: In questo caso, x.x.xxxx è la versione del plug-in.
----
 rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx
 rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx
 rm -rf com.netapp.vsch5-x.x.x.xxxx
----
.. Modificare le directory nella directory delle estensioni dell'interfaccia utente del client vCenter (HTML5) utilizzando `cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`
.. Rimuovere i pacchetti di plug-in memorizzati nella cache specifici del plug-in NetApp utilizzando `rm -rf` comandi:
Esempio: In questo caso, x.x.xxxx è la versione del plug-in
 ----
rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx
rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx
rm -rf com.netapp.vsch5-x.x.x.xxxx
 ----


|===
. Accedere a vSphere e riavviare il client Web vSphere e i servizi client vSphere utilizzando i seguenti comandi:
+
[listing]
----
service-control --stop vsphere-client vsphere-ui
service-control --start vsphere-client vsphere-ui
----

