---
permalink: deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: Per impostazione predefinita, i tool ONTAP per VMware vSphere dispongono della funzionalità del provider VASA. È possibile configurare gli archivi dati di VMware Virtual Volumes con i profili di funzionalità storage richiesti per ciascun datastore vVols. 
---
= Abilitare il provider VASA per la configurazione di datastore virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, i tool ONTAP per VMware vSphere dispongono della funzionalità del provider VASA. È possibile configurare gli archivi dati di VMware Virtual Volumes (vVols) con i profili di funzionalità storage richiesti per ciascun datastore vVols.

*Cosa ti serve*

* È necessario aver configurato l'istanza di vCenter Server e ESXi.
* È necessario aver implementato gli strumenti ONTAP .


*A proposito di questa attività*

Se la funzionalità del provider VASA viene disattivata prima dell'aggiornamento alla versione 9.7.1 degli strumenti ONTAP , la funzionalità del provider VASA rimane disattivata dopo l'aggiornamento. Questa release consente di attivare la funzione di replica vVols per gli archivi dati vVols.

*Fasi*

. Accedere all'interfaccia utente Web di VMware vSphere.
. Dal client vSphere, fare clic su *Menu* > *Console degli strumenti ONTAP*.
. Fare clic su *Impostazioni*.
. Fare clic su *Gestisci funzionalità* nella scheda Impostazioni amministrative.
. Nella finestra di dialogo Manage Capabilities (Gestisci funzionalità), selezionare l'interno del provider VASA da attivare.
. Se si desidera utilizzare la funzionalità di replica per gli archivi dati vVols, utilizzare il pulsante di commutazione *Enable vVols Replication* (attiva replica vVols).
. Inserire l'indirizzo IP degli strumenti ONTAP e la password dell'amministratore, quindi fare clic su *Apply* (Applica).
+

NOTE: Se lo stato del provider VASA viene visualizzato come "`Offline`" anche dopo aver attivato l'interno del provider VASA, controllare ``/var/log/vmware/vmware-sps/sps.log` Per eventuali errori di connessione con il provider VASA o riavviare il servizio "`vmware-sps`".





== Registrare i servizi API di OnCommand con ONTAP 9.6 o versioni precedenti

Se si utilizza ONTAP 9.6 o versioni precedenti, la dashboard di vVol consente di visualizzare i dettagli dei datastore e delle macchine virtuali di VMware Virtual Volumes (vVol) solo se sono stati registrati i servizi API di OnCommand per il provider VASA per ottenere i dati per i report di vVol VM e datastore.

*Cosa ti serve*

È necessario aver scaricato i servizi API di OnCommand 2.1 o versioni successive dal sito del supporto NetApp.


NOTE: La dashboard di vVol visualizza le metriche delle performance solo quando i datastore E le macchine virtuali DI SAN vVol sono configurati utilizzando ONTAP 9.3 o versione successiva.

*Fasi*

. Dalla home page degli strumenti di ONTAP, fare clic su *Impostazioni*.
. Fare clic su *Manage Extension* (Gestisci estensione) nella scheda Administrative Settings (Impostazioni amministrative).
. Utilizzare il dispositivo di scorrimento Registra servizi API OnCommand per attivare i servizi API OnCommand.
. Immettere l'indirizzo IP, la porta di servizio e le credenziali per i servizi API OnCommand.
+
È inoltre possibile utilizzare la finestra di dialogo Manage VASA Provider Extensions (Gestisci estensioni provider VASA) per le seguenti modifiche:

+
** Per aggiornare la registrazione dei servizi API di OnCommand in caso di modifica delle credenziali.
** Per annullare la registrazione dei servizi API di OnCommand quando non è più necessaria la dashboard di vVol.
+
Deselezionare la casella di controllo Registra servizi API OnCommand per rimuovere la registrazione dei servizi API OnCommand per il provider VASA.



. Fare clic su *Apply* (Applica).
+
La dashboard vVol visualizza le metriche per gli archivi dati DI ONTAP 9.6 o versioni precedenti DI SAN vVol solo dopo il completamento della registrazione dei servizi API di OnCommand.



*Informazioni correlate*

https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"]
