---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: I report del datastore forniscono informazioni dettagliate sugli archivi dati tradizionali e sulle macchine virtuali create su questi datastore. 
---
= Report datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I report del datastore forniscono informazioni dettagliate sugli archivi dati tradizionali e sulle macchine virtuali create su questi datastore.

La dashboard tradizionale consente di esaminare e identificare potenziali problemi con gli archivi dati e le macchine virtuali nel server vCenter. È possibile visualizzare, ordinare ed esportare i report. I dati per i report datastore e macchine virtuali tradizionali sono forniti da vCenter Server. Tuttavia, a causa dell'introduzione del supporto per datastore supportato da FlexGroup, alcune metriche come latenza, throughput e IOPS sono ottenute da ONTAP.


NOTE: Il monitoraggio dei file non è supportato per gli archivi dati FlexGroup configurati su macchine virtuali a storage diretto (SVM).

Il datastore fornisce i seguenti report predefiniti:

* Report datastore
* Report macchine virtuali


*Report datastore*

+
Il menu Datastore Report fornisce informazioni sui seguenti parametri per gli archivi dati:

* Nome dell'archivio dati
* Tipo di datastore: NFS o VMFS
* Stile del volume
+
Lo stile del volume può essere un volume FlexVol o un volume FlexGroup.

* Spazio libero
* Spazio utilizzato
* Spazio totale
* Percentuale di spazio utilizzato
* Percentuale di spazio disponibile
* IOPS
+
Il report visualizza gli IOPS per l'archivio dati.

* Latenza
+
Il report visualizza le informazioni di latenza per l'archivio dati.

+
È inoltre possibile verificare l'ora in cui è stato generato il report. Il menu Datastore Report (rapporto archivio dati) consente di organizzare il report in base alle proprie esigenze ed esportare il report organizzato utilizzando il pulsante *Export to CSV* (Esporta in CSV). I nomi dei datastore nel report sono collegamenti che consentono di accedere alla scheda Monitor del datastore selezionato, in cui è possibile visualizzare le metriche di performance del datastore.



*Report macchina virtuale*

+
Il menu Virtual Machine Report (Report macchina virtuale) fornisce le metriche delle performance per tutte le macchine virtuali che utilizzano datastore forniti da VSC per un vCenter Server selezionato. Le metriche delle macchine virtuali visualizzate nei report delle macchine virtuali sono dati storici che vengono raccolti ogni 30 minuti per le macchine virtuali su datastore tradizionali. I dati "`ultimo aggiornamento`" e "`successivo aggiornamento `" vengono aggiunti alla tabella per fornire dettagli su quando sono stati raccolti e quando sarà la successiva raccolta di dati.

* Nome della macchina virtuale
* Nome del datastore
* Stile del volume
+
Lo stile del volume può essere un volume FlexVol o un volume FlexGroup.

* Origine
+
L'origine per la raccolta dei dettagli della macchina virtuale può essere ONTAP o vCenter Server.

* Latenza
+
Il report visualizza la latenza per le macchine virtuali in tutti gli archivi dati associati alle macchine virtuali.

* IOPS
* Throughput
* Capacità impegnata
+
Il report visualizza il valore della capacità impegnata per una macchina virtuale.

* Host
+
Il report visualizza i sistemi host su cui è disponibile la macchina virtuale.

* Uptime
+
Il report mostra l'ora in cui la macchina virtuale è accesa ed è disponibile su un host ESXi.

* Stato di alimentazione
+
Il report indica se la macchina virtuale è accesa o spenta.



Ogni nome di macchina virtuale nel report è un collegamento alla scheda Monitor della macchina virtuale selezionata. È possibile ordinare il report della macchina virtuale in base alle proprie esigenze ed esportarlo in un file .CSV e salvarlo sul sistema locale. L'indicazione dell'ora del report viene aggiunta anche al report salvato.

Per le macchine virtuali supportate dai volumi FlexGroup, quando viene attivata la nuova macchina virtuale, i file vengono registrati per il monitoraggio su ONTAP. Le metriche storiche per latenza, throughput e IOPS sono ottenute quando si accede ai report delle macchine virtuali da ONTAP.
