---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: È possibile monitorare le performance e visualizzare i cinque principali datastore DI volumi virtuali VMware SAN e NAS nel server vCenter in base ai parametri selezionati utilizzando la dashboard vVol dei tool ONTAP. 
---
= Analizza i dati delle performance utilizzando la dashboard di vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile monitorare le performance e visualizzare i cinque principali datastore vVol (VMware Virtual Volumes) SAN e NAS nel server vCenter in base ai parametri selezionati utilizzando la dashboard vVol dei tool ONTAP.

*Cosa ti serve*

* Se si utilizza ONTAP 9.6 o versioni precedenti, è necessario attivare i servizi API di OnCommand 2.1 o versioni successive.
+
Non è necessario registrare i servizi API OnCommand con il provider VASA per ottenere i dettagli del datastore SAN vVols o del report datastore SAN vVols VM per ONTAP 9.7 o versioni successive.

+
https://mysupport.netapp.com/site/global/dashboard[]

* Si consiglia di utilizzare ONTAP 9.3 o versione successiva per il sistema storage.


I dati IOPS forniti da ONTAP vengono arrotondati e visualizzati nella dashboard di vVol. Potrebbe esserci una differenza tra il valore IOPS effettivo fornito da ONTAP e il valore IOPS visualizzato nella dashboard di vVol. A partire dalla release 9.8 dei tool ONTAP, il monitoraggio delle performance è disponibile per i datastore vVol basati su NFS.


NOTE: Se si registrano i servizi API di OnCommand per la prima volta, è possibile visualizzare tutti i dati delle metriche delle performance per gli archivi dati DI SAN vVol nella dashboard di vVol solo dopo 15 - 30 minuti.

* I dati della dashboard di vVol vengono aggiornati periodicamente, a intervalli di 10 minuti.
* Se è stato aggiunto, modificato o eliminato un sistema di storage dall'istanza di vCenter Server, è possibile che non si notino modifiche nei dati nella dashboard di vVols per un certo periodo di tempo.
+
Questo perché i servizi API di OnCommand richiedono tempo per ottenere metriche aggiornate da ONTAP.

* Il valore IOPS totale visualizzato nel portlet Overview del dashboard vVol non è un valore cumulativo del valore IOPS di lettura e del valore IOPS di scrittura.
+
Gli IOPS in lettura, gli IOPS in scrittura e gli IOPS totali sono metriche separate fornite dai servizi API di OnCommand. Se esiste una differenza tra il valore IOPS totale e il valore IOPS cumulativo (valore IOPS di lettura + valore IOPS di scrittura) fornito dai servizi API di OnCommand, la stessa differenza viene osservata nei valori IOPS nella dashboard vVol.

* I vVol di dati basati su NFS con provisioning su ONTAP 9.8 e versioni successive vengono registrati automaticamente per il monitoraggio delle performance nella dashboard di vVol.


*Fasi*

. Dalla home page del client vSphere, fare clic su *ONTAP tools*.
. Selezionare il vCenter Server desiderato utilizzando il menu a discesa *vCenter server* per visualizzare gli archivi dati.
. Fare clic su *vVols Dashboard*.
+
Il portlet Datastores fornisce i seguenti dettagli:

+
** Il numero di datastore vVol gestiti dal provider VASA nell'istanza di vCenter Server
** I primi cinque datastore vVol in base all'utilizzo delle risorse e ai parametri di performance
È possibile modificare l'elenco degli archivi dati in base allo spazio utilizzato, agli IOPS o alla latenza e nell'ordine richiesto.


. Visualizza i dettagli delle macchine virtuali utilizzando il portlet macchine virtuali.
+
Il portlet macchine virtuali fornisce i seguenti dettagli:

+
** Numero di macchine virtuali che utilizzano datastore ONTAP nel server vCenter
** Le prime cinque macchine virtuali basate su IOPS, latenza, throughput, capacità impegnata, uptime, e spazio logico
È possibile personalizzare il modo in cui le prime cinque macchine virtuali sono elencate nella dashboard di vVols.






== Requisiti dei dati della dashboard di vVol

È necessario verificare alcuni requisiti importanti della dashboard vVols per visualizzare i dettagli dinamici dei datastore e delle macchine virtuali VMware Virtual Volumes (vVols).

La seguente tabella presenta una panoramica di cosa si dovrebbe verificare se la dashboard vVols non visualizza le metriche delle performance per gli archivi dati E le macchine virtuali SAN vVols con provisioning.

|===


| *Considerazioni* | *Descrizione* 


 a| 
Prima implementazione dei servizi API di OnCommand
 a| 
* Se si utilizzano cluster ONTAP 9.6 o versioni precedenti, si utilizzano i servizi API di OnCommand 2.1 o versioni successive.
+
Se si utilizza ONTAP 9.7 e versioni successive, non è necessario che i servizi API di OnCommand siano registrati presso il provider VASA.

* Dopo aver scaricato e installato i servizi API di OnCommand dal sito di supporto di OnCommand, è necessario seguire le istruzioni di installazione fornite nella _Guida all'installazione e all'installazione dei servizi API di API di NetApp.
* Ogni istanza del provider VASA deve disporre di un'istanza dei servizi API OnCommand dedicata.
+
I servizi API di OnCommand non devono essere condivisi tra più istanze di provider VASA o server vCenter.

* I servizi API di OnCommand sono in esecuzione e accessibili.




 a| 
Sistema storage
 a| 
* Si utilizza ONTAP 9.3 o versione successiva.
* Si stanno utilizzando le credenziali appropriate per il sistema di storage.
* Il sistema storage è attivo e accessibile.
* La macchina virtuale selezionata deve utilizzare almeno un datastore vVol e le operazioni di i/o vengono eseguite sul disco della macchina virtuale.


|===